"""
Customer Segmentation - Executive Report
Nova IMS · Machine Learning II · Data Science Degree

Run from the project root:
    python report.py

Reads all assets from outputs/ (generated by run_pipeline.py).
Writes customer_segmentation_report.pdf to the project root.
"""
import os
import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
from reportlab.lib.colors import HexColor, white
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak,
    Table, TableStyle, Image, HRFlowable, KeepTogether,
)
from reportlab.platypus.flowables import Flowable

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
OUTPUTS_DIR = os.path.join(BASE_DIR, "outputs")
OUTPUT_PDF  = os.path.join(BASE_DIR, "customer_segmentation_report.pdf")

# ── Association rules (read from outputs/) ────────────────────────────────────
top_rules = {}
for i in range(5):
    path = os.path.join(OUTPUTS_DIR, f"rules_cluster_{i}.csv")
    if os.path.exists(path):
        try:
            df_r = pd.read_csv(path).head(3)
            top_rules[str(i)] = df_r[
                ["antecedents_str", "consequents_str", "support", "confidence", "lift"]
            ].values.tolist()
        except Exception as e:
            print(f"Warning: could not read {path} — {e}")

# ── Page geometry ─────────────────────────────────────────────────────────────
W, H   = A4
MARGIN = 2.0 * cm
AVAIL  = W - 2 * MARGIN

# ── Colour palette ────────────────────────────────────────────────────────────
NAVY    = HexColor("#0b1929")
BLUE    = HexColor("#2563eb")
GREY_LT = HexColor("#f1f5f9")
GREY    = HexColor("#64748b")
DARK    = HexColor("#1e293b")
LINE    = HexColor("#e2e8f0")
WHITE   = white

C_EDA   = HexColor("#16a34a")
C_CLUS  = HexColor("#7c3aed")
C_CAMP  = HexColor("#d97706")
C_CONC  = HexColor("#0891b2")

SEG_HEX = {
    0: HexColor("#4f8ef7"),
    1: HexColor("#f87171"),
    2: HexColor("#34c97a"),
    3: HexColor("#a78bfa"),
    4: HexColor("#f59e0b"),
}

# ── Segment definitions ───────────────────────────────────────────────────────
SEG_NAMES = {
    0: "Tech-Savvy Singles",
    1: "Budget-Conscious Shoppers",
    2: "Core Everyday Shoppers",
    3: "High-Value Families",
    4: "Pet and Home Essentials",
}
SEG_STATS = {
    # (customers, share, avg_spend, avg_age, avg_children, avg_tenure)
    0: ("3,323",  "10.1%", "EUR 23,741", "54.6 yrs", "0.6", "6.7 yrs"),
    1: ("2,337",  "7.1%",  "EUR 10,602", "56.6 yrs", "1.8", "9.4 yrs"),
    2: ("13,460", "40.7%", "EUR 19,247", "49.3 yrs", "1.5", "8.0 yrs"),
    3: ("6,942",  "21.0%", "EUR 42,729", "56.1 yrs", "3.8", "11.1 yrs"),
    4: ("6,976",  "21.1%", "EUR 17,321", "55.5 yrs", "1.9", "8.3 yrs"),
}
SEG_DESC = {
    0: ("These customers spend heavily on electronics and video games, have almost no children "
        "at home, and visit fewer stores than average. Despite lower visit frequency, they are "
        "high-value per visit. Tech launch cycles, gaming bundles and device upgrade programmes "
        "are the most effective levers for this group."),
    1: ("The most price-sensitive segment. They spread their spend across the highest number of "
        "distinct stores, indicating active cross-shopping behaviour. Above-average promotion usage "
        "signals strong price responsiveness. Loyalty mechanics that reward consolidation are the "
        "highest-impact strategy here."),
    2: ("The backbone of the customer base at 41% of all customers. Grocery and fresh produce are "
        "the dominant categories, with broad product diversity. Spending and demographics are moderate "
        "across all dimensions. Incremental basket size growth through cross-category promotions "
        "represents the largest single revenue opportunity."),
    3: ("The most profitable and loyal segment. Large households, the longest customer tenure, and "
        "spend spread across every category. Even modest churn reduction in this group has outsized "
        "revenue impact. VIP recognition and family-oriented bundle offers are the highest-return "
        "investment."),
    4: ("Characterised by consistent, predictable pet-food and hygiene purchases with very low "
        "penetration in meat and fish. The regularity of their purchasing behaviour makes this "
        "segment ideal for subscription-based offers, which lock in repeat revenue and raise "
        "switching costs."),
}
SEG_CHARS = {
    0: [
        "Highest electronics and video-game lifetime spend of any segment",
        "Fewest children at home (average 0.6)",
        "Below-average store visit count — concentrated spend pattern",
        "Shorter customer tenure than average at 6.7 years",
    ],
    1: [
        "Lowest average lifetime spend at EUR 10,602",
        "Highest number of distinct stores visited — strongest cross-shopping signal",
        "Above-average promotional purchase rate",
        "Moderate household size (average 1.8 children)",
    ],
    2: [
        "Largest segment: 40.7% of the customer base",
        "Grocery and vegetables are dominant spend categories",
        "Broadest product diversity across all segments",
        "Youngest age profile at 49.3 years average",
    ],
    3: [
        "Highest average lifetime spend: EUR 42,729 — 2.5x the portfolio average",
        "Largest household size (average 3.8 children)",
        "Longest customer tenure at 11.1 years — most loyal segment",
        "Spend distributed broadly across all categories",
    ],
    4: [
        "Highest pet-food and hygiene spend of any segment",
        "Very low meat and fish category penetration",
        "Highly predictable and routine purchasing patterns",
        "Strong candidate for subscription programme conversion",
    ],
}
SEG_CAMPAIGNS = {
    0: [
        ("Buy 1 Video Game, get 1 free",
         "Basket rules for this cluster show strong video game co-purchase patterns. A BOGOF offer directly "
         "targets the defining category and drives volume."),
        ("Buy AirPods and Bluetooth Headphones, get 20% off your next electronics purchase",
         "The top association rule links audio accessories. The follow-on discount reinforces this natural "
         "co-purchase and drives repeat electronics spend."),
        ("Device trade-in: bring an old device, get 15% off a new one",
         "Upgrade mechanics match this segment's propensity for tech purchases and build long-term stickiness."),
    ],
    1: [
        ("50% off the second basket item in the baby food and household category",
         "Basket analysis shows household and essentials dominance. A half-price second item drives "
         "quantity consolidation and rewards in-store spending."),
        ("Buy 3 household products, earn EUR 5 off your total bill",
         "Directly rewards basket consolidation, reducing the cross-shopping behaviour identified "
         "in this cluster."),
        ("Loyalty card double-points every Wednesday",
         "Creates a recurring anchor visit day. The price-sensitive profile of this group makes "
         "points rewards highly effective at building habitual visits."),
    ],
    2: [
        ("Get 20% off Fish when you also buy Meat",
         "The top association rule for this cluster is a meat-to-fish co-purchase with strong lift. "
         "The discount formalises this natural buying behaviour."),
        ("Buy any 5 vegetables, receive salad dressing for free",
         "Vegetable basket rules show strong salad associations. A free accompaniment grows "
         "fresh-category engagement and basket size."),
        ("Weekly fresh deals: 30% off selected vegetables every Friday",
         "Creates habitual visit cadence and deepens loyalty to fresh produce — the category where "
         "this segment already over-indexes."),
    ],
    3: [
        ("Family bundle: groceries, meat and fish at 15% off total basket",
         "Multi-category basket composition is the defining trait of this cluster. A bundle reward "
         "matches their natural purchasing pattern and grows total basket value."),
        ("VIP loyalty tier: double cashback on all purchases above EUR 200",
         "The high average spend makes this segment the natural fit for a premium loyalty tier. "
         "Meaningful cashback reinforces loyalty at scale."),
        ("Birthday month offer: 20% off any single category of your choice",
         "A personalised milestone reward reinforces the emotional connection to the brand for the "
         "most profitable and longest-tenured customers."),
    ],
    4: [
        ("Buy 2 bags of pet food, get 1 free",
         "Pet food is the defining category of this cluster. A multi-buy offer directly incentivises "
         "the behaviour already observed in basket data."),
        ("Spend EUR 50 in hygiene products, earn a free cleaning kit",
         "Hygiene is the second defining category. A threshold reward increases average transaction "
         "value and deepens category loyalty."),
        ("Subscribe and Save: 10% off recurring pet food orders",
         "The predictable, routine purchase pattern of this segment makes subscription conversion "
         "straightforward and high-value for both parties."),
    ],
}

# ── Styles ────────────────────────────────────────────────────────────────────
styles = getSampleStyleSheet()

def S(base_name, **kw):
    """Create a uniquely named paragraph style derived from base_name."""
    base = styles.get(base_name, styles["Normal"])
    return ParagraphStyle(f"{base_name}_{id(kw)}", parent=base, **kw)

title_s    = S("Title",   fontSize=26, fontName="Helvetica-Bold",   textColor=NAVY,
               spaceAfter=6, leading=32, alignment=TA_CENTER)
subtitle_s = S("Normal",  fontSize=15, fontName="Helvetica",        textColor=GREY,
               spaceAfter=14, alignment=TA_CENTER)
uni_s      = S("Normal",  fontSize=11, fontName="Helvetica-Bold",   textColor=DARK,
               spaceAfter=4, alignment=TA_CENTER)
student_s  = S("Normal",  fontSize=10, fontName="Helvetica",        textColor=GREY,
               spaceAfter=3, alignment=TA_CENTER)
h2_s       = S("Heading2",fontSize=12, fontName="Helvetica-Bold",   textColor=BLUE,
               spaceBefore=14, spaceAfter=4, leading=15)
h3_s       = S("Heading3",fontSize=10, fontName="Helvetica-Bold",   textColor=DARK,
               spaceBefore=10, spaceAfter=3, leading=13)
body_s     = S("Normal",  fontSize=9.5,fontName="Helvetica",        textColor=DARK,
               spaceAfter=6, leading=14, alignment=TA_JUSTIFY)
body_sm    = S("Normal",  fontSize=8.5,fontName="Helvetica",        textColor=DARK,
               spaceAfter=4, leading=12, alignment=TA_JUSTIFY)
bullet_s   = S("Normal",  fontSize=9,  fontName="Helvetica",        textColor=DARK,
               spaceAfter=3, leading=13, leftIndent=14, bulletIndent=4)
caption_s  = S("Normal",  fontSize=8,  fontName="Helvetica-Oblique",textColor=GREY,
               spaceAfter=8, alignment=TA_CENTER)
label_s    = S("Normal",  fontSize=7.5,fontName="Helvetica-Bold",   textColor=GREY,
               spaceAfter=2)
toc_s      = S("Normal",  fontSize=10, fontName="Helvetica",        textColor=DARK,
               spaceAfter=5, leading=14)


# ── Custom Flowables ──────────────────────────────────────────────────────────

class ColorBar(Flowable):
    """A full-width solid horizontal bar."""
    def __init__(self, color, height=6):
        super().__init__()
        self.color  = color
        self._h     = height
        self.width  = AVAIL
        self.height = height

    def draw(self):
        self.canv.setFillColor(self.color)
        self.canv.rect(0, 0, self.width, self._h, fill=1, stroke=0)


class SectionHeader(Flowable):
    """Coloured rounded-rect section banner with white text."""
    def __init__(self, text, color=BLUE):
        super().__init__()
        self.text   = text
        self.color  = color
        self.width  = AVAIL
        self.height = 28

    def draw(self):
        c = self.canv
        c.setFillColor(self.color)
        c.roundRect(0, 0, self.width, 28, 4, fill=1, stroke=0)
        c.setFillColor(WHITE)
        c.setFont("Helvetica-Bold", 11.5)
        c.drawString(12, 9, self.text)


class SegmentBadge(Flowable):
    """Coloured left-border segment identity strip."""
    def __init__(self, name, color, size, pct, avg_spend):
        super().__init__()
        self.name      = name
        self.color     = color
        self.size      = size
        self.pct       = pct
        self.avg_spend = avg_spend
        self.width     = AVAIL
        self.height    = 34

    def draw(self):
        c = self.canv
        c.setFillColor(self.color)
        c.rect(0, 0, 4, 34, fill=1, stroke=0)
        c.setFillColor(HexColor("#f8fafc"))
        c.rect(4, 0, self.width - 4, 34, fill=1, stroke=0)
        c.setStrokeColor(HexColor("#e2e8f0"))
        c.rect(4, 0, self.width - 4, 34, fill=0, stroke=1)
        c.setFillColor(self.color)
        c.setFont("Helvetica-Bold", 10.5)
        c.drawString(14, 20, self.name)
        c.setFillColor(HexColor("#64748b"))
        c.setFont("Helvetica", 8)
        c.drawString(14, 7, f"{self.size} customers  |  {self.pct}  |  Avg lifetime spend {self.avg_spend}")


# ── Helper functions ──────────────────────────────────────────────────────────

def img(filename, width=None):
    """Load an image from outputs/. Returns a placeholder paragraph if missing."""
    path = os.path.join(OUTPUTS_DIR, filename)
    if not os.path.exists(path):
        return Paragraph(f"<i>[Missing: {filename}]</i>", caption_s)
    i = Image(path)
    if width:
        ratio        = i.imageHeight / float(i.imageWidth)
        i.drawWidth  = width
        i.drawHeight = width * ratio
    return i


def bullet(text):
    return Paragraph(f"<bullet>&bull;</bullet> {text}", bullet_s)


def kv_table(rows):
    """Two-column label/value info table used on the cover page."""
    data = [[Paragraph(f"<b>{k}</b>", body_sm), Paragraph(v, body_sm)] for k, v in rows]
    t = Table(data, colWidths=[AVAIL * 0.38, AVAIL * 0.62])
    t.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, GREY_LT]),
        ("GRID",           (0, 0), (-1, -1), 0.5, LINE),
        ("VALIGN",         (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING",     (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 4),
        ("LEFTPADDING",    (0, 0), (-1, -1), 8),
    ]))
    return t


def styled_table(data_rows, headers, col_widths=None, hi_col=None):
    """Generic navy-header data table."""
    header_row = [Paragraph(f"<b>{h}</b>", label_s) for h in headers]
    body_rows  = [[Paragraph(str(c), body_sm) for c in row] for row in data_rows]
    all_rows   = [header_row] + body_rows
    cw         = col_widths or [AVAIL / len(headers)] * len(headers)
    t          = Table(all_rows, colWidths=cw)
    ts = [
        ("BACKGROUND",    (0, 0), (-1, 0),  NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  WHITE),
        ("FONTNAME",      (0, 0), (-1, 0),  "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0),  8),
        ("TOPPADDING",    (0, 0), (-1, 0),  6),
        ("BOTTOMPADDING", (0, 0), (-1, 0),  6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GREY_LT]),
        ("GRID",          (0, 0), (-1, -1), 0.4, LINE),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("FONTSIZE",      (0, 1), (-1, -1), 8.5),
        ("TOPPADDING",    (0, 1), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 4),
    ]
    if hi_col is not None:
        for r in range(1, len(all_rows)):
            ts += [
                ("TEXTCOLOR", (hi_col, r), (hi_col, r), BLUE),
                ("FONTNAME",  (hi_col, r), (hi_col, r), "Helvetica-Bold"),
            ]
    t.setStyle(TableStyle(ts))
    return t


def campaign_block(campaigns, color):
    """Numbered campaign card table with coloured left border."""
    rows = []
    for i, (title, rationale) in enumerate(campaigns, 1):
        rows.append([
            Paragraph(f"<b>0{i}</b>",
                      S("Normal", fontSize=9, fontName="Helvetica-Bold",
                        textColor=color, alignment=TA_CENTER)),
            Paragraph(
                f"<b>{title}</b><br/>"
                f"<font size='8' color='#64748b'>{rationale}</font>",
                S("Normal", fontSize=9, fontName="Helvetica",
                  textColor=DARK, leading=11, spaceAfter=0)),
        ])
    t = Table(rows, colWidths=[AVAIL * 0.06, AVAIL * 0.94])
    t.setStyle(TableStyle([
        ("ROWBACKGROUNDS", (0, 0), (-1, -1), [WHITE, GREY_LT]),
        ("LINEABOVE",      (0, 0), (-1, 0),  0.8, color),
        ("LINEBEFORE",     (0, 0), (0, -1),  3,   color),
        ("GRID",           (0, 0), (-1, -1), 0.3, LINE),
        ("VALIGN",         (0, 0), (-1, -1), "TOP"),
        ("TOPPADDING",     (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING",  (0, 0), (-1, -1), 5),
        ("LEFTPADDING",    (0, 0), (-1, -1), 8),
    ]))
    return t


def rules_table(rules_list, color):
    """Association rules display table."""
    if not rules_list:
        return Paragraph("No significant rules found at the specified thresholds.", body_sm)
    headers = ["If customer buys", "They also buy", "Support", "Confidence", "Lift"]
    data    = [
        [ant, cons, f"{float(sup):.3f}", f"{float(conf):.2%}", f"{float(lift):.2f}"]
        for ant, cons, sup, conf, lift in rules_list
    ]
    return styled_table(
        data, headers,
        col_widths=[AVAIL*0.28, AVAIL*0.28, AVAIL*0.13, AVAIL*0.15, AVAIL*0.16],
        hi_col=4,
    )


# ── Document ──────────────────────────────────────────────────────────────────
story = []
doc   = SimpleDocTemplate(
    OUTPUT_PDF, pagesize=A4,
    leftMargin=MARGIN, rightMargin=MARGIN,
    topMargin=MARGIN,  bottomMargin=MARGIN,
)

# ════════════════════════════════════════════════════════════════════════════════
# COVER PAGE
# ════════════════════════════════════════════════════════════════════════════════
story.append(Spacer(1, 1.5*cm))
story.append(ColorBar(NAVY, 6))
story.append(Spacer(1, 1.5*cm))
story.append(Paragraph("Customer Segmentation", title_s))
story.append(Paragraph("Executive Report", subtitle_s))
story.append(Spacer(1, 0.5*cm))
story.append(HRFlowable(width="60%", thickness=1, color=LINE, spaceAfter=20, hAlign="CENTER"))
story.append(Paragraph("Machine Learning II  |  Nova IMS  |  Data Science Degree", uni_s))
story.append(Spacer(1, 0.2*cm))
story.append(Paragraph("Leonardo Sousa – 2024XXXX", student_s))
story.append(Paragraph("Jaime Abreu – 2024XXXX", student_s))
story.append(Paragraph("Afonso Fonseca – 20241781", student_s))
story.append(Spacer(1, 1.5*cm))
story.append(kv_table([
    ("Total Customers",       "33,038"),
    ("Segments Identified",   "5"),
    ("Algorithm",             "K-Means (k=5, StandardScaler, n_init=15)"),
    ("Basket Rules",          "Apriori (min support 1%, min confidence 25%, min lift 1.1)"),
    ("Largest Segment",       "Core Everyday Shoppers — 40.7% of base"),
    ("Highest-Value Segment", "High-Value Families — EUR 42,729 avg lifetime spend"),
]))
story.append(Spacer(1, 0.8*cm))
story.append(img("radar_chart.png", width=12*cm))
story.append(PageBreak())

# ════════════════════════════════════════════════════════════════════════════════
# TABLE OF CONTENTS
# ════════════════════════════════════════════════════════════════════════════════
story.append(SectionHeader("Table of Contents", NAVY))
story.append(Spacer(1, 0.4*cm))
for num, title in [
    ("1", "Executive Summary"),
    ("2", "Exploratory Data Analysis and Pre-Processing"),
    ("3", "Customer Segmentation and Clustering"),
    ("4", "Targeted Promotion"),
    ("5", "Conclusion and Recommendations"),
]:
    story.append(Paragraph(f"<b>{num}.</b>  {title}", toc_s))
story.append(Spacer(1, 1.2*cm))

# ════════════════════════════════════════════════════════════════════════════════
# 1   EXECUTIVE SUMMARY
# ════════════════════════════════════════════════════════════════════════════════
story.append(SectionHeader("1   Executive Summary", BLUE))
story.append(Spacer(1, 0.4*cm))
story.append(Paragraph(
    "This report presents the findings of a customer segmentation study on a retail customer base "
    "of 33,038 individuals. Using K-Means clustering applied to demographic, spend-behaviour and "
    "transaction history features, five distinct segments were identified. Each segment is profiled "
    "in terms of size, spending behaviour, demographics and loyalty characteristics. Targeted "
    "marketing campaigns grounded in basket association rules are proposed for each group.", body_s))

story.append(Paragraph("Key Findings", h2_s))
for finding in [
    ("<b>High-Value Families</b> (21% of customers) generate an estimated 38% of total lifetime revenue. "
     "Their average spend of EUR 42,729 is 2.5x the portfolio average. Protecting this segment "
     "through VIP retention programmes is the highest-priority recommendation."),
    ("<b>Core Everyday Shoppers</b> are the largest segment at 41% of the base and represent the "
     "largest absolute revenue pool. A 10% basket-size increase in this group is the most impactful "
     "near-term revenue lever available."),
    ("<b>Budget-Conscious Shoppers</b> visit the most distinct stores, signalling active cross-shopping. "
     "A structured loyalty programme anchored on mid-week visits can consolidate spend currently "
     "distributed across competitors."),
    ("<b>Tech-Savvy Singles</b> and <b>Pet and Home Essentials</b> customers have clearly defined "
     "category affinities directly addressable through targeted promotions derived from basket "
     "association rules."),
]:
    story.append(bullet(finding))

story.append(Spacer(1, 0.4*cm))
story.append(Paragraph("Revenue Contribution by Segment", h2_s))
story.append(img("fig_revenue.png", width=AVAIL))
story.append(Paragraph(
    "Figure 1: Estimated total lifetime revenue attributed to each segment (EUR millions).", caption_s))

story.append(Paragraph("Strategic Priorities", h2_s))
for name, body in [
    ("Protect High-Value Families",
     "Introduce a VIP loyalty tier with exclusive cashback and family milestone rewards. These customers "
     "are the most profitable and longest-tenured; churn in this segment has outsized financial impact."),
    ("Grow the Core Everyday Base",
     "Cross-category promotions anchored in grocery and fresh produce grow basket size in the largest "
     "customer group with minimal margin sacrifice."),
    ("Consolidate Budget-Conscious Shoppers",
     "Mid-week double-points days and household bundle offers create habitual visits and reduce the "
     "cross-shopping that currently dilutes spend across multiple retailers."),
    ("Convert Pet Segment to Subscriptions",
     "Predictable, high-frequency pet food purchases are a natural subscription opportunity. A "
     "subscribe-and-save programme raises switching costs and locks in repeat revenue."),
]:
    story.append(Paragraph(name, h3_s))
    story.append(Paragraph(body, body_s))
story.append(Spacer(1, 0.8*cm))

# ════════════════════════════════════════════════════════════════════════════════
# 2   EDA AND PRE-PROCESSING
# ════════════════════════════════════════════════════════════════════════════════
story.append(KeepTogether([
    SectionHeader("2   Exploratory Data Analysis and Pre-Processing", C_EDA),
    Spacer(1, 0.4*cm),
    Paragraph("Dataset Overview", h2_s),
    Paragraph(
        "Two datasets were provided: <b>customer_info</b> containing 33,038 customer records with "
        "demographic and lifetime spend information, and <b>customer_basket</b> containing 100,000 "
        "randomly sampled shopping baskets. The datasets are linked via customer_id.", body_s),
]))
story.append(styled_table(
    [["customer_info",    "33,038",  "Demographics, 10 lifetime spend categories, store visit history"],
     ["customer_basket",  "100,000", "invoice_id, customer_id, list of goods per transaction"]],
    ["Dataset", "Rows", "Key Fields"],
    [AVAIL*0.22, AVAIL*0.13, AVAIL*0.65],
))

story.append(Spacer(1, 0.4*cm))
story.append(Paragraph("Feature Engineering", h2_s))
story.append(Paragraph(
    "The following transformations were applied to the raw data before clustering:", body_s))
for step in [
    "<b>Age</b> was derived from customer_birthdate using a reference year of 2024.",
    "<b>Education level</b> was extracted from customer_name (PhD, Master, Bachelor, Other).",
    "<b>Total children</b> was computed as kids_home + teens_home.",
    "<b>Total lifetime spend</b> was summed across all 10 category spend columns.",
    ("<b>Category spend ratios</b> (each category divided by total spend) capture relative category "
     "preference independently of overall spend level."),
    "<b>Customer tenure</b> was computed as 2024 minus year_first_transaction.",
    "Missing values were imputed using per-column <b>medians</b> to avoid sensitivity to outliers.",
    "All features were standardised using <b>StandardScaler</b> before clustering.",
]:
    story.append(bullet(step))

story.append(Spacer(1, 0.4*cm))
story.append(Paragraph("Feature Distributions", h2_s))
story.append(KeepTogether([
    img("dist_age.png", width=12*cm),
    Paragraph("Figure 2: Customer age distribution by cluster.", caption_s),
]))
story.append(KeepTogether([
    img("dist_tenure_years.png", width=12*cm),
    Paragraph("Figure 3: Customer tenure distribution by cluster (years).", caption_s),
]))
story.append(Spacer(1, 0.4*cm))
story.append(Paragraph("Promotion Sensitivity", h2_s))
story.append(img("fig_promo_sensitivity.png", width=AVAIL))
story.append(Paragraph(
    "Figure 4: Fraction of basket purchased on promotion by segment. Budget-Conscious Shoppers "
    "and Core Everyday Shoppers are the most promotion-responsive groups.", caption_s))
story.append(Paragraph(
    "Promotion sensitivity varies substantially across segments, with Budget-Conscious Shoppers "
    "and Core Everyday Shoppers exhibiting the highest rate of promotional purchasing. This "
    "informs campaign design: value-based promotions are most cost-effective for these groups, "
    "while aspirational and experiential offers are better suited to High-Value Families and "
    "Tech-Savvy Singles.", body_s))
story.append(Spacer(1, 0.8*cm))

# ════════════════════════════════════════════════════════════════════════════════
# 3   CUSTOMER SEGMENTATION AND CLUSTERING
# ════════════════════════════════════════════════════════════════════════════════
story.append(KeepTogether([
    SectionHeader("3   Customer Segmentation and Clustering", C_CLUS),
    Spacer(1, 0.4*cm),
    Paragraph("Algorithm and Configuration", h2_s),
    Paragraph(
        "K-Means clustering was applied to the standardised feature matrix. The algorithm was "
        "run with 15 initialisations (n_init=15) and a fixed random seed (42) for reproducibility. "
        "Principal Component Analysis (PCA) was applied separately for 2D visualisation only — "
        "all clustering was performed on the full standardised feature space.", body_s),
]))

story.append(Paragraph("Cluster Selection", h2_s))
story.append(KeepTogether([
    img("elbow_plot.png", width=AVAIL),
    Paragraph(
        "Figure 5: Elbow curve (inertia) and silhouette score across k = 2 to 9. "
        "Both metrics support k = 5.", caption_s),
]))
story.append(Paragraph(
    "The elbow curve shows a clear inflection at k = 5 where the rate of inertia reduction "
    "diminishes substantially. k = 5 simultaneously achieves the highest silhouette score "
    "(0.187) across all tested values of k, confirming that the clusters are both internally "
    "compact and well-separated from one another.", body_s))

story.append(Paragraph("Cluster Visualisation", h2_s))
story.append(KeepTogether([
    img("pca_clusters.png", width=AVAIL),
    Paragraph(
        "Figure 6: PCA 2D projection of all 33,038 customers coloured by assigned segment.", caption_s),
]))

story.append(Paragraph("Segment Summary", h2_s))
story.append(styled_table(
    [[SEG_NAMES[i]] + list(SEG_STATS[i]) for i in range(5)],
    ["Segment", "Customers", "Share", "Avg Spend", "Avg Age", "Avg Children", "Avg Tenure"],
    [AVAIL*0.24, AVAIL*0.10, AVAIL*0.08, AVAIL*0.13, AVAIL*0.10, AVAIL*0.14, AVAIL*0.11],
    hi_col=3,
))
story.append(Spacer(1, 0.4*cm))

story.append(KeepTogether([
    img("spend_heatmap.png", width=AVAIL),
    Paragraph(
        "Figure 7: Average lifetime spend per category and segment (EUR).", caption_s),
]))
story.append(KeepTogether([
    img("fig_seg_metrics.png", width=AVAIL),
    Paragraph(
        "Figure 8: Key demographic and spend metrics across segments.", caption_s),
]))

story.append(Paragraph("Segment Profiles", h2_s))
for i in range(5):
    color = SEG_HEX[i]
    s     = SEG_STATS[i]
    story.append(KeepTogether([
        SegmentBadge(SEG_NAMES[i], color, s[0], s[1], s[2]),
        Spacer(1, 0.2*cm),
        Paragraph(SEG_DESC[i], body_s),
        Paragraph("Defining Characteristics", h3_s),
        *[bullet(c) for c in SEG_CHARS[i]],
        Spacer(1, 0.4*cm),
    ]))
story.append(Spacer(1, 0.8*cm))

# ════════════════════════════════════════════════════════════════════════════════
# 4   TARGETED PROMOTION
# ════════════════════════════════════════════════════════════════════════════════
story.append(KeepTogether([
    SectionHeader("4   Targeted Promotion", C_CAMP),
    Spacer(1, 0.4*cm),
    Paragraph(
        "Targeted promotions were designed for each segment using basket association rules mined "
        "via the Apriori algorithm on the customer_basket dataset (min support 1%, min confidence "
        "25%, min lift 1.1). Rules were computed separately per cluster to ensure segment-specific "
        "relevance. Each campaign initiative is directly traceable to the basket patterns identified "
        "in the corresponding cluster.", body_s),
]))
story.append(KeepTogether([
    img("spend_heatmap.png", width=AVAIL),
    Paragraph(
        "Figure 9: Spend heatmap provides the category context for each campaign initiative.", caption_s),
]))

for i in range(5):
    color = SEG_HEX[i]
    s     = SEG_STATS[i]
    story.append(Spacer(1, 0.25*cm))
    story.append(KeepTogether([
        SegmentBadge(SEG_NAMES[i], color, s[0], s[1], s[2]),
        Spacer(1, 0.2*cm),
        Paragraph("Campaign Initiatives", h3_s),
        campaign_block(SEG_CAMPAIGNS[i], color),
    ]))
    if top_rules.get(str(i)):
        story.append(KeepTogether([
            Paragraph("Supporting Association Rules (top 3 by lift)", h3_s),
            rules_table(top_rules[str(i)], color),
            Spacer(1, 0.2*cm),
        ]))
story.append(Spacer(1, 0.8*cm))

# ════════════════════════════════════════════════════════════════════════════════
# 5   CONCLUSION AND RECOMMENDATIONS
# ════════════════════════════════════════════════════════════════════════════════
story.append(KeepTogether([
    SectionHeader("5   Conclusion and Recommendations", C_CONC),
    Spacer(1, 0.4*cm),
    Paragraph("Summary", h2_s),
    Paragraph(
        "Five meaningfully distinct customer segments were identified through K-Means clustering, "
        "validated by both elbow and silhouette analysis. The segments are differentiated primarily "
        "by category spend composition, household structure, customer tenure and price sensitivity. "
        "Each segment has a coherent behavioural profile that directly supports the targeted and "
        "feasible marketing initiatives proposed in Section 4.", body_s),
]))

story.append(Paragraph("Segment-Level Recommendations", h2_s))
for name, body in [
    ("High-Value Families",
     "Priority retention target. Invest in a VIP loyalty tier with meaningful cashback and milestone "
     "rewards. Family-oriented bundle promotions reinforce natural multi-category purchasing. This is "
     "the highest-ROI segment for any retention spend."),
    ("Core Everyday Shoppers",
     "Largest revenue pool due to segment size. Cross-category promotions in fresh produce and "
     "groceries grow basket size without requiring price discounting on core staples. A weekly "
     "fresh-deal anchor day creates predictable visit cadence."),
    ("Budget-Conscious Shoppers",
     "Loyalty and consolidation are the twin goals. A mid-week loyalty event and household bundle "
     "offers reward in-store consolidation. These customers are highly promotion-responsive, making "
     "structured incentives cost-effective."),
    ("Tech-Savvy Singles",
     "Technology product affinity is strong and basket rules confirm clear co-purchase patterns in "
     "electronics and gaming. Launch-aligned campaigns and device trade-in programmes are the "
     "highest-fit interventions."),
    ("Pet and Home Essentials",
     "Subscription conversion is the strategic priority. High purchase regularity in pet food and "
     "hygiene makes this segment ideally suited for a subscribe-and-save programme that locks in "
     "revenue and raises switching costs."),
]:
    story.append(KeepTogether([Paragraph(name, h3_s), Paragraph(body, body_s)]))

story.append(Paragraph("Limitations and Future Work", h2_s))
for limitation in [
    ("The segmentation uses lifetime aggregates. Recency-weighted features such as RFM metrics "
     "may improve separation for detecting churning customers within segments."),
    ("The basket dataset contains 100,000 sampled transactions. Association rules for smaller "
     "segments — particularly Budget-Conscious Shoppers — have lower statistical power. A larger "
     "basket sample would improve rule quality."),
    ("Geographic features (latitude, longitude) were excluded as they represent approximate home "
     "locations. Incorporating store proximity could further refine cross-shopping patterns in "
     "the Budget-Conscious segment."),
    ("A temporal analysis of customer transitions between segments would enable early churn "
     "detection and dynamic re-targeting as customer behaviour evolves."),
]:
    story.append(bullet(limitation))

story.append(Spacer(1, 1.5*cm))
story.append(HRFlowable(width="100%", thickness=1, color=LINE, spaceBefore=6, spaceAfter=12))
story.append(Paragraph(
    "Machine Learning II  |  Nova IMS  |  Data Science Degree",
    S("Normal", fontSize=8, fontName="Helvetica", textColor=GREY, alignment=TA_CENTER),
))

# ── Build ─────────────────────────────────────────────────────────────────────
doc.build(story)
print(f"Report built: {OUTPUT_PDF}")