"""
Customer Segmentation - Executive Report
Nova IMS · Machine Learning II · Data Science Degree

Run from the project root:
    python report_word.py

Reads all assets from outputs/ (generated by run_pipeline.py).
Writes customer_segmentation_report.docx to the project root.
"""
import os
import pandas as pd
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT, WD_ALIGN_VERTICAL
from docx.oxml import OxmlElement
from docx.oxml.ns import qn

# ── Paths ─────────────────────────────────────────────────────────────────────
BASE_DIR    = os.path.dirname(os.path.abspath(__file__))
OUTPUTS_DIR = os.path.join(BASE_DIR, "outputs")
OUTPUT_DOCX = os.path.join(BASE_DIR, "customer_segmentation_report.docx")

# ── Association rules (read from outputs/) ────────────────────────────────────
top_rules = {}
for i in range(5):
    path = os.path.join(OUTPUTS_DIR, f"rules_cluster_{i}.csv")
    if os.path.exists(path):
        try:
            df_r = pd.read_csv(path).head(3)
            top_rules[str(i)] = df_r[
                ["antecedents_str", "consequents_str", "support", "confidence", "lift"]
            ].values.tolist()
        except Exception as e:
            print(f"Warning: could not read {path} - {e}")

# ── Colour palette ────────────────────────────────────────────────────────────
HEX_NAVY    = "0B1929"
HEX_BLUE    = "2563EB"
HEX_GREY_LT = "F1F5F9"
HEX_GREY    = "64748B"
HEX_DARK    = "1E293B"
HEX_LINE    = "E2E8F0"

SEG_HEX = {
    0: "4F8EF7",
    1: "F87171",
    2: "34C97A",
    3: "A78BFA",
    4: "F59E0B",
}

# ── Segment definitions ───────────────────────────────────────────────────────
SEG_NAMES = {
    0: "Tech-Savvy Singles",
    1: "Budget-Conscious Shoppers",
    2: "Core Everyday Shoppers",
    3: "High-Value Families",
    4: "Pet and Home Essentials",
}
SEG_STATS = {
    0: ("3,323",  "10.1%", "EUR 23,741", "54.6 yrs", "0.6", "6.7 yrs"),
    1: ("2,337",  "7.1%",  "EUR 10,602", "56.6 yrs", "1.8", "9.4 yrs"),
    2: ("13,460", "40.7%", "EUR 19,247", "49.3 yrs", "1.5", "8.0 yrs"),
    3: ("6,942",  "21.0%", "EUR 42,729", "56.1 yrs", "3.8", "11.1 yrs"),
    4: ("6,976",  "21.1%", "EUR 17,321", "55.5 yrs", "1.9", "8.3 yrs"),
}
SEG_DESC = {
    0: ("These customers spend heavily on electronics and video games, have almost no children "
        "at home, and visit fewer stores than average. Despite lower visit frequency, they are "
        "high-value per visit. Tech launch cycles, gaming bundles and device upgrade programmes "
        "are the most effective levers for this group."),
    1: ("The most price-sensitive segment. They spread their spend across the highest number of "
        "distinct stores, indicating active cross-shopping behaviour. Above-average promotion usage "
        "signals strong price responsiveness. Loyalty mechanics that reward consolidation are the "
        "highest-impact strategy here."),
    2: ("The backbone of the customer base at 41% of all customers. Grocery and fresh produce are "
        "the dominant categories, with broad product diversity. Spending and demographics are moderate "
        "across all dimensions. Incremental basket size growth through cross-category promotions "
        "represents the largest single revenue opportunity."),
    3: ("The most profitable and loyal segment. Large households, the longest customer tenure, and "
        "spend spread across every category. Even modest churn reduction in this group has outsized "
        "revenue impact. VIP recognition and family-oriented bundle offers are the highest-return "
        "investment."),
    4: ("Characterised by consistent, predictable pet-food and hygiene purchases with very low "
        "penetration in meat and fish. The regularity of their purchasing behaviour makes this "
        "segment ideal for subscription-based offers, which lock in repeat revenue and raise "
        "switching costs."),
}
SEG_CHARS = {
    0: [
        "Highest electronics and video-game lifetime spend of any segment",
        "Fewest children at home (average 0.6)",
        "Below-average store visit count - concentrated spend pattern",
        "Shorter customer tenure than average at 6.7 years",
    ],
    1: [
        "Lowest average lifetime spend at EUR 10,602",
        "Highest number of distinct stores visited - strongest cross-shopping signal",
        "Above-average promotional purchase rate",
        "Moderate household size (average 1.8 children)",
    ],
    2: [
        "Largest segment: 40.7% of the customer base",
        "Grocery and vegetables are dominant spend categories",
        "Broadest product diversity across all segments",
        "Youngest age profile at 49.3 years average",
    ],
    3: [
        "Highest average lifetime spend: EUR 42,729 - 2.5x the portfolio average",
        "Largest household size (average 3.8 children)",
        "Longest customer tenure at 11.1 years - most loyal segment",
        "Spend distributed broadly across all categories",
    ],
    4: [
        "Highest pet-food and hygiene spend of any segment",
        "Very low meat and fish category penetration",
        "Highly predictable and routine purchasing patterns",
        "Strong candidate for subscription programme conversion",
    ],
}
SEG_CAMPAIGNS = {
    0: [
        ("Buy 1 Video Game, get 1 free",
         "Basket rules for this cluster show strong video game co-purchase patterns. A BOGOF offer directly "
         "targets the defining category and drives volume."),
        ("Buy AirPods and Bluetooth Headphones, get 20% off your next electronics purchase",
         "The top association rule links audio accessories. The follow-on discount reinforces this natural "
         "co-purchase and drives repeat electronics spend."),
        ("Device trade-in: bring an old device, get 15% off a new one",
         "Upgrade mechanics match this segment's propensity for tech purchases and build long-term stickiness."),
    ],
    1: [
        ("50% off the second basket item in the baby food and household category",
         "Basket analysis shows household and essentials dominance. A half-price second item drives "
         "quantity consolidation and rewards in-store spending."),
        ("Buy 3 household products, earn EUR 5 off your total bill",
         "Directly rewards basket consolidation, reducing the cross-shopping behaviour identified "
         "in this cluster."),
        ("Loyalty card double-points every Wednesday",
         "Creates a recurring anchor visit day. The price-sensitive profile of this group makes "
         "points rewards highly effective at building habitual visits."),
    ],
    2: [
        ("Get 20% off Fish when you also buy Meat",
         "The top association rule for this cluster is a meat-to-fish co-purchase with strong lift. "
         "The discount formalises this natural buying behaviour."),
        ("Buy any 5 vegetables, receive salad dressing for free",
         "Vegetable basket rules show strong salad associations. A free accompaniment grows "
         "fresh-category engagement and basket size."),
        ("Weekly fresh deals: 30% off selected vegetables every Friday",
         "Creates habitual visit cadence and deepens loyalty to fresh produce - the category where "
         "this segment already over-indexes."),
    ],
    3: [
        ("Family bundle: groceries, meat and fish at 15% off total basket",
         "Multi-category basket composition is the defining trait of this cluster. A bundle reward "
         "matches their natural purchasing pattern and grows total basket value."),
        ("VIP loyalty tier: double cashback on all purchases above EUR 200",
         "The high average spend makes this segment the natural fit for a premium loyalty tier. "
         "Meaningful cashback reinforces loyalty at scale."),
        ("Birthday month offer: 20% off any single category of your choice",
         "A personalised milestone reward reinforces the emotional connection to the brand for the "
         "most profitable and longest-tenured customers."),
    ],
    4: [
        ("Buy 2 bags of pet food, get 1 free",
         "Pet food is the defining category of this cluster. A multi-buy offer directly incentivises "
         "the behaviour already observed in basket data."),
        ("Spend EUR 50 in hygiene products, earn a free cleaning kit",
         "Hygiene is the second defining category. A threshold reward increases average transaction "
         "value and deepens category loyalty."),
        ("Subscribe and Save: 10% off recurring pet food orders",
         "The predictable, routine purchase pattern of this segment makes subscription conversion "
         "straightforward and high-value for both parties."),
    ],
}

# ── XML Shading Helpers for Native Word Elements ──────────────────────────────

def set_cell_background(cell, fill_hex):
    """Sets background color of a table cell."""
    tc_pr = cell._element.get_or_add_tcPr()
    shd = OxmlElement('w:shd')
    shd.set(qn('w:val'), 'clear')
    shd.set(qn('w:color'), 'auto')
    shd.set(qn('w:fill'), fill_hex)
    tc_pr.append(shd)

def set_cell_margins(cell, top=100, bottom=100, left=150, right=150):
    """Sets internal padding for a table cell."""
    tc_pr = cell._element.get_or_add_tcPr()
    tc_mar = OxmlElement('w:tcMar')
    for m, val in [('w:top', top), ('w:bottom', bottom), ('w:left', left), ('w:right', right)]:
        node = OxmlElement(m)
        node.set(qn('w:w'), str(val))
        node.set(qn('w:type'), 'dxa')
        tc_mar.append(node)
    tc_pr.append(tc_mar)

def set_cell_borders(cell, **kwargs):
    """
    Sets specific cell borders. Usage:
    set_cell_borders(cell, top={"sz": 12, "val": "single", "color": "HEX"})
    """
    tc_pr = cell._element.get_or_add_tcPr()
    tc_borders = OxmlElement('w:tcBorders')
    for border_name, border_props in kwargs.items():
        border = OxmlElement(f'w:{border_name}')
        for key, val in border_props.items():
            border.set(qn(f'w:{key}'), str(val))
        tc_borders.append(border)
    tc_pr.append(tc_borders)

def add_heading_styled(doc, text, level, space_before=12, space_after=6, hex_color=HEX_DARK):
    """Creates a standardized heading with programmatic spacing and color."""
    p = doc.add_heading(text, level=level)
    p.paragraph_format.space_before = Pt(space_before)
    p.paragraph_format.space_after = Pt(space_after)
    p.paragraph_format.keep_with_next = True
    for run in p.runs:
        run.font.color.rgb = RGBColor.from_string(hex_color)
        run.font.name = 'Arial'
    return p

# ── Refactored Visual Components ──────────────────────────────────────────────

def add_image(doc, filename, width_inch=5.5):
    """Loads and appends an image from outputs/. Appends text placeholder if missing."""
    path = os.path.join(OUTPUTS_DIR, filename)
    if not os.path.exists(path):
        p = doc.add_paragraph()
        run = p.add_run(f"[Missing Image Asset: {filename}]")
        run.font.italic = True
        run.font.color.rgb = RGBColor.from_string(HEX_GREY)
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        return
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_after = Pt(4)
    p.add_run().add_picture(path, width=Inches(width_inch))

def add_caption(doc, text):
    """Appends an italicized caption below figures."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p.paragraph_format.space_after = Pt(12)
    run = p.add_run(text)
    run.font.size = Pt(8.5)
    run.font.italic = True
    run.font.color.rgb = RGBColor.from_string(HEX_GREY)

def add_bullet(doc, text):
    """Adds a standard bullet point with controlled text formatting."""
    p = doc.add_paragraph(style='List Bullet')
    p.paragraph_format.space_after = Pt(3)
    p.paragraph_format.line_spacing = 1.15
    # Word interprets HTML tags like <b> manually inside runs:
    parts = text.split("<b>")
    if len(parts) == 1:
        run = p.add_run(text)
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor.from_string(HEX_DARK)
    else:
        for part in parts:
            if "</b>" in part:
                bold_txt, normal_txt = part.split("</b>")
                r1 = p.add_run(bold_txt)
                r1.bold = True
                r1.font.size = Pt(10)
                r1.font.color.rgb = RGBColor.from_string(HEX_DARK)
                r2 = p.add_run(normal_txt)
                r2.font.size = Pt(10)
                r2.font.color.rgb = RGBColor.from_string(HEX_DARK)
            else:
                r0 = p.add_run(part)
                r0.font.size = Pt(10)
                r0.font.color.rgb = RGBColor.from_string(HEX_DARK)

def create_segment_badge_table(doc, name, color_hex, num_cust, pct, avg_spend):
    """Replicates SegmentBadge flowable using a single-cell bordered Word table."""
    table = doc.add_table(rows=1, cols=1)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    
    cell = table.cell(0, 0)
    cell.width = Inches(6.5)
    set_cell_background(cell, "F8FAFC")
    set_cell_margins(cell, top=120, bottom=120, left=180, right=180)
    
    # Left thick border configuration
    set_cell_borders(cell, 
                     left={"sz": 24, "val": "single", "color": color_hex},
                     top={"sz": 4, "val": "single", "color": HEX_LINE},
                     bottom={"sz": 4, "val": "single", "color": HEX_LINE},
                     right={"sz": 4, "val": "single", "color": HEX_LINE})
    
    p = cell.paragraphs[0]
    p.paragraph_format.space_after = Pt(2)
    r1 = p.add_run(name)
    r1.bold = True
    r1.font.size = Pt(11)
    r1.font.color.rgb = RGBColor.from_string(color_hex)
    
    p2 = cell.add_paragraph()
    p2.paragraph_format.space_after = Pt(0)
    r2 = p2.add_run(f"{num_cust} customers  |  {pct}  |  Avg lifetime spend {avg_spend}")
    r2.font.size = Pt(8.5)
    r2.font.color.rgb = RGBColor.from_string(HEX_GREY)
    
    # Structural spacer below the table container
    doc.add_paragraph().paragraph_format.space_after = Pt(4)

def generate_styled_table(doc, data_rows, headers, col_widths=None, hi_col=None):
    """Builds a structured, styled data grid matching the original template."""
    table = doc.add_table(rows=len(data_rows) + 1, cols=len(headers))
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    
    # Format Header Row
    hdr_cells = table.rows[0].cells
    for idx, header_text in enumerate(headers):
        hdr_cells[idx].text = header_text
        set_cell_background(hdr_cells[idx], HEX_NAVY)
        set_cell_margins(hdr_cells[idx], top=100, bottom=100, left=120, right=120)
        p = hdr_cells[idx].paragraphs[0]
        p.alignment = WD_ALIGN_PARAGRAPH.LEFT
        for run in p.runs:
            run.font.bold = True
            run.font.size = Pt(9)
            run.font.color.rgb = RGBColor.from_string("FFFFFF")
            
    # Format Data Rows
    for r_idx, row_data in enumerate(data_rows):
        row_cells = table.rows[r_idx + 1].cells
        bg_color = HEX_GREY_LT if r_idx % 2 == 1 else "FFFFFF"
        
        for c_idx, val in enumerate(row_data):
            row_cells[c_idx].text = str(val)
            set_cell_background(row_cells[c_idx], bg_color)
            set_cell_margins(row_cells[c_idx], top=80, bottom=80, left=120, right=120)
            
            # Apply light gray borders to mimic grid lines
            set_cell_borders(row_cells[c_idx],
                             top={"sz": 4, "val": "single", "color": HEX_LINE},
                             bottom={"sz": 4, "val": "single", "color": HEX_LINE},
                             left={"sz": 4, "val": "single", "color": HEX_LINE},
                             right={"sz": 4, "val": "single", "color": HEX_LINE})
            
            p = row_cells[c_idx].paragraphs[0]
            for run in p.runs:
                run.font.size = Pt(9)
                if hi_col is not None and c_idx == hi_col:
                    run.font.bold = True
                    run.font.color.rgb = RGBColor.from_string(HEX_BLUE)
                else:
                    run.font.color.rgb = RGBColor.from_string(HEX_DARK)
                    
    # Distribute dynamic column width allocations
    if col_widths:
        for row in table.rows:
            for idx, w in enumerate(col_widths):
                row.cells[idx].width = Inches(w)
                
    p_spacer = doc.add_paragraph()
    p_spacer.paragraph_format.space_after = Pt(6)

def generate_campaign_block(doc, campaigns, color_hex):
    """Builds a structured table containing the numbered campaign rationales."""
    table = doc.add_table(rows=len(campaigns), cols=2)
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    table.autofit = False
    
    for idx, (title, rationale) in enumerate(campaigns):
        row_cells = table.rows[idx].cells
        bg_color = HEX_GREY_LT if idx % 2 == 1 else "FFFFFF"
        
        # Column 0: Index ID Numbering
        cell_num = row_cells[0]
        cell_num.width = Inches(0.5)
        cell_num.text = f"0{idx + 1}"
        set_cell_background(cell_num, bg_color)
        set_cell_margins(cell_num, top=100, bottom=100, left=100, right=100)
        set_cell_borders(cell_num,
                         left={"sz": 18, "val": "single", "color": color_hex},
                         top={"sz": 12 if idx == 0 else 4, "val": "single", "color": color_hex if idx == 0 else HEX_LINE},
                         bottom={"sz": 4, "val": "single", "color": HEX_LINE},
                         right={"sz": 4, "val": "single", "color": HEX_LINE})
        p_num = cell_num.paragraphs[0]
        p_num.alignment = WD_ALIGN_PARAGRAPH.CENTER
        for run in p_num.runs:
            run.font.bold = True
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor.from_string(color_hex)
            
        # Column 1: Core content descriptors
        cell_content = row_cells[1]
        cell_content.width = Inches(6.0)
        set_cell_background(cell_content, bg_color)
        set_cell_margins(cell_content, top=100, bottom=100, left=120, right=120)
        set_cell_borders(cell_content,
                         top={"sz": 12 if idx == 0 else 4, "val": "single", "color": color_hex if idx == 0 else HEX_LINE},
                         bottom={"sz": 4, "val": "single", "color": HEX_LINE},
                         right={"sz": 4, "val": "single", "color": HEX_LINE},
                         left={"sz": 4, "val": "single", "color": HEX_LINE})
        
        p_content = cell_content.paragraphs[0]
        p_content.paragraph_format.space_after = Pt(2)
        r_title = p_content.add_run(title)
        r_title.bold = True
        r_title.font.size = Pt(9.5)
        r_title.font.color.rgb = RGBColor.from_string(HEX_DARK)
        
        p_rat = cell_content.add_paragraph()
        p_rat.paragraph_format.space_after = Pt(0)
        r_rat = p_rat.add_run(rationale)
        r_rat.font.size = Pt(8.5)
        r_rat.font.color.rgb = RGBColor.from_string(HEX_GREY)
        
    doc.add_paragraph().paragraph_format.space_after = Pt(6)


# ── Core Document Pipeline Execution ──────────────────────────────────────────

def build_docx_report():
    doc = Document()
    
    # Establish base margins on document sections
    for section in doc.sections:
        section.top_margin = Inches(0.8)
        section.bottom_margin = Inches(0.8)
        section.left_margin = Inches(0.8)
        section.right_margin = Inches(0.8)

    # ════════════════════════════════════════════════════════════════════════════
    # COVER PAGE
    # ════════════════════════════════════════════════════════════════════════════
    p_top = doc.add_paragraph()
    p_top.paragraph_format.space_before = Pt(36)
    
    # Native Paragraph top accent bar decoration replacement
    t_bar = doc.add_table(rows=1, cols=1)
    t_bar.alignment = WD_TABLE_ALIGNMENT.CENTER
    cell_bar = t_bar.cell(0, 0)
    cell_bar.width = Inches(6.5)
    set_cell_background(cell_bar, HEX_NAVY)
    cell_bar.paragraphs[0].paragraph_format.space_after = Pt(0)
    # Set explicit small row thickness height
    trPr = t_bar.rows[0]._element.get_or_add_trPr()
    trHeight = OxmlElement('w:trHeight')
    trHeight.set(qn('w:val'), '120')  # dxa calculation matching height
    trPr.append(trHeight)
    
    p_title = doc.add_paragraph()
    p_title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_title.paragraph_format.space_before = Pt(36)
    p_title.paragraph_format.space_after = Pt(4)
    r_title = p_title.add_run("Customer Segmentation")
    r_title.font.size = Pt(28)
    r_title.font.bold = True
    r_title.font.color.rgb = RGBColor.from_string(HEX_NAVY)
    
    p_sub = doc.add_paragraph()
    p_sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_sub.paragraph_format.space_after = Pt(24)
    r_sub = p_sub.add_run("Executive Report")
    r_sub.font.size = Pt(16)
    r_sub.font.color.rgb = RGBColor.from_string(HEX_GREY)
    
    p_uni = doc.add_paragraph()
    p_uni.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_uni.paragraph_format.space_after = Pt(2)
    r_uni = p_uni.add_run("Machine Learning II  |  Nova IMS  |  Data Science Degree")
    r_uni.font.bold = True
    r_uni.font.size = Pt(11)
    r_uni.font.color.rgb = RGBColor.from_string(HEX_DARK)
    
    for name in ["Leonardo Souza | 20241411", "Jaime Abreu | 20241823", "Afonso Fonseca | 20241781"]:
        p_st = doc.add_paragraph()
        p_st.alignment = WD_ALIGN_PARAGRAPH.CENTER
        p_st.paragraph_format.space_after = Pt(2)
        r_st = p_st.add_run(name)
        r_st.font.size = Pt(10)
        r_st.font.color.rgb = RGBColor.from_string(HEX_GREY)
        
    p_space = doc.add_paragraph()
    p_space.paragraph_format.space_after = Pt(24)
    
    # Portfolio overview grid construction
    kv_data = [
        ["Total Customers",       "33,038"],
        ["Segments Identified",   "5"],
        ["Algorithm",              "K-Means (k=5, StandardScaler, n_init=15)"],
        ["Basket Rules",          "Apriori (min support 1%, min confidence 25%, min lift 1.1)"],
        ["Largest Segment",       "Core Everyday Shoppers - 40.7% of base"],
        ["Highest-Value Segment", "High-Value Families - EUR 42,729 avg lifetime spend"],
    ]
    generate_styled_table(doc, kv_data, ["Metric Dimension", "Value Assessment"], col_widths=[2.5, 4.0])
    
    add_image(doc, "radar_chart.png", width_inch=4.5)
    doc.add_page_break()

    # ════════════════════════════════════════════════════════════════════════════
    # TABLE OF CONTENTS
    # ════════════════════════════════════════════════════════════════════════════
    add_heading_styled(doc, "Table of Contents", level=1, hex_color=HEX_NAVY)
    for num, title in [
        ("1", "Executive Summary"),
        ("2", "Exploratory Data Analysis and Pre-Processing"),
        ("3", "Customer Segmentation and Clustering"),
        ("4", "Targeted Promotion"),
        ("5", "Conclusion and Recommendations"),
    ]:
        p_toc = doc.add_paragraph()
        p_toc.paragraph_format.space_after = Pt(4)
        r_num = p_toc.add_run(f"{num}.   ")
        r_num.bold = True
        r_num.font.color.rgb = RGBColor.from_string(HEX_DARK)
        r_title = p_toc.add_run(title)
        r_title.font.color.rgb = RGBColor.from_string(HEX_DARK)
        
    doc.add_page_break()

    # ════════════════════════════════════════════════════════════════════════════
    # 1   EXECUTIVE SUMMARY
    # ════════════════════════════════════════════════════════════════════════════
    add_heading_styled(doc, "1   Executive Summary", level=1, hex_color=HEX_BLUE)
    p = doc.add_paragraph(
        "This report presents the findings of a customer segmentation study on a retail customer base "
        "of 33,038 individuals. Using K-Means clustering applied to demographic, spend-behaviour and "
        "transaction history features, five distinct segments were identified. Each segment is profiled "
        "in terms of size, spending behaviour, demographics and loyalty characteristics. Targeted "
        "marketing campaigns grounded in basket association rules are proposed for each group."
    )
    p.paragraph_format.space_after = Pt(12)

    add_heading_styled(doc, "Key Findings", level=2, hex_color=HEX_BLUE)
    findings = [
        "<b>High-Value Families</b> (21% of customers) generate an estimated 38% of total lifetime revenue. "
        "Their average spend of EUR 42,729 is 2.5x the portfolio average. Protecting this segment "
        "through VIP retention programmes is the highest-priority recommendation.",
        "<b>Core Everyday Shoppers</b> are the largest segment at 41% of the base and represent the "
        "largest absolute revenue pool. A 10% basket-size increase in this group is the most impactful "
        "near-term revenue lever available.",
        "<b>Budget-Conscious Shoppers</b> visit the most distinct stores, signalling active cross-shopping. "
        "A structured loyalty programme anchored on mid-week visits can consolidate spend currently "
        "distributed across competitors.",
        "<b>Tech-Savvy Singles</b> and <b>Pet and Home Essentials</b> customers have clearly defined "
        "category affinities directly addressable through targeted promotions derived from basket "
        "association rules."
    ]
    for f in findings:
        add_bullet(doc, f)

    add_heading_styled(doc, "Revenue Contribution by Segment", level=2, hex_color=HEX_BLUE)
    add_image(doc, "fig_revenue.png", width_inch=6.5)
    add_caption(doc, "Figure 1: Estimated total lifetime revenue attributed to each segment (EUR millions).")

    add_heading_styled(doc, "Strategic Priorities", level=2, hex_color=HEX_BLUE)
    priorities = [
        ("Protect High-Value Families",
         "Introduce a VIP loyalty tier with exclusive cashback and family milestone rewards. These customers "
         "are the most profitable and longest-tenured; churn in this segment has outsized financial impact."),
        ("Grow the Core Everyday Base",
         "Cross-category promotions anchored in grocery and fresh produce grow basket size in the largest "
         "customer group with minimal margin sacrifice."),
        ("Consolidate Budget-Conscious Shoppers",
         "Mid-week double-points days and household bundle offers create habitual visits and reduce the "
         "cross-shopping that currently dilutes spend across multiple retailers."),
        ("Convert Pet Segment to Subscriptions",
         "Predictable, high-frequency pet food purchases are a natural subscription opportunity. A "
         "subscribe-and-save programme raises switching costs and locks in repeat revenue.")
    ]
    for heading, body in priorities:
        add_heading_styled(doc, heading, level=3, hex_color=HEX_DARK)
        p_body = doc.add_paragraph(body)
        p_body.paragraph_format.space_after = Pt(8)

    # ════════════════════════════════════════════════════════════════════════════
    # 2   EDA AND PRE-PROCESSING
    # ════════════════════════════════════════════════════════════════════════════
    add_heading_styled(doc, "2   Exploratory Data Analysis and Pre-Processing", level=1, hex_color="16A34A")
    add_heading_styled(doc, "Dataset Overview", level=2, hex_color="16A34A")
    doc.add_paragraph(
        "Two datasets were provided: customer_info containing 33,038 customer records with "
        "demographic and lifetime spend information, and customer_basket containing 100,000 "
        "randomly sampled shopping baskets. The datasets are linked via customer_id."
    )
    
    eda_table_data = [
        ["customer_info",    "33,038",  "Demographics, 10 lifetime spend categories, store visit history"],
        ["customer_basket",  "100,000", "invoice_id, customer_id, list of goods per transaction"]
    ]
    generate_styled_table(doc, eda_table_data, ["Dataset", "Rows", "Key Fields"], col_widths=[1.5, 1.0, 4.0])

    add_heading_styled(doc, "Feature Engineering", level=2, hex_color="16A34A")
    doc.add_paragraph("The following transformations were applied to the raw data before clustering:")
    steps = [
        "<b>Age</b> was derived from customer_birthdate using a reference year of 2024.",
        "<b>Education level</b> was extracted from customer_name (PhD, Master, Bachelor, Other).",
        "<b>Total children</b> was computed as kids_home + teens_home.",
        "<b>Total lifetime spend</b> was summed across all 10 category spend columns.",
        "<b>Category spend ratios</b> (each category divided by total spend) capture relative category preference independently of overall spend level.",
        "<b>Customer tenure</b> was computed as 2024 minus year_first_transaction.",
        "Missing values were imputed using per-column <b>medians</b> to avoid sensitivity to outliers.",
        "All features were standardised using <b>StandardScaler</b> before clustering."
    ]
    for s in steps:
        add_bullet(doc, s)

    add_heading_styled(doc, "Feature Distributions", level=2, hex_color="16A34A")
    add_image(doc, "dist_age.png", width_inch=5.0)
    add_caption(doc, "Figure 2: Customer age distribution by cluster.")
    
    add_image(doc, "dist_tenure_years.png", width_inch=5.0)
    add_caption(doc, "Figure 3: Customer tenure distribution by cluster (years).")

    add_heading_styled(doc, "Promotion Sensitivity", level=2, hex_color="16A34A")
    add_image(doc, "fig_promo_sensitivity.png", width_inch=6.5)
    add_caption(doc, "Figure 4: Fraction of basket purchased on promotion by segment. Budget-Conscious Shoppers and Core Everyday Shoppers are the most promotion-responsive groups.")
    
    doc.add_paragraph(
        "Promotion sensitivity varies substantially across segments, with Budget-Conscious Shoppers "
        "and Core Everyday Shoppers exhibiting the highest rate of promotional purchasing. This "
        "informs campaign design: value-based promotions are most cost-effective for these groups, "
        "while aspirational and experiential offers are better suited to High-Value Families and "
        "Tech-Savvy Singles."
    )

    # ════════════════════════════════════════════════════════════════════════════
    # 3   CUSTOMER SEGMENTATION AND CLUSTERING
    # ════════════════════════════════════════════════════════════════════════════
    add_heading_styled(doc, "3   Customer Segmentation and Clustering", level=1, hex_color="7C3AED")
    add_heading_styled(doc, "Algorithm and Configuration", level=2, hex_color="7C3AED")
    doc.add_paragraph(
        "K-Means clustering was applied to the standardised feature matrix. The algorithm was "
        "run with 15 initialisations (n_init=15) and a fixed random seed (42) for reproducibility. "
        "Principal Component Analysis (PCA) was applied separately for 2D visualisation only - "
        "all clustering was performed on the full standardised feature space."
    )

    add_heading_styled(doc, "Cluster Selection", level=2, hex_color="7C3AED")
    add_image(doc, "elbow_plot.png", width_inch=6.5)
    add_caption(doc, "Figure 5: Elbow curve (inertia) and silhouette score across k = 2 to 9. Both metrics support k = 5.")
    doc.add_paragraph(
        "The elbow curve shows a clear inflection at k = 5 where the rate of inertia reduction "
        "diminishes substantially. k = 5 simultaneously achieves the highest silhouette score "
        "(0.187) across all tested values of k, confirming that the clusters are both internally "
        "compact and well-separated from one another."
    )

    add_heading_styled(doc, "Cluster Visualisation", level=2, hex_color="7C3AED")
    add_image(doc, "pca_clusters.png", width_inch=6.5)
    add_caption(doc, "Figure 6: PCA 2D projection of all 33,038 customers coloured by assigned segment.")

    add_heading_styled(doc, "Segment Summary", level=2, hex_color="7C3AED")
    seg_summary_rows = []
    for idx in range(5):
        seg_summary_rows.append([SEG_NAMES[idx]] + list(SEG_STATS[idx]))
    generate_styled_table(doc, seg_summary_rows, 
                          ["Segment", "Customers", "Share", "Avg Spend", "Avg Age", "Avg Children", "Avg Tenure"],
                          col_widths=[1.5, 0.8, 0.6, 1.0, 0.7, 1.1, 0.8], hi_col=3)

    add_image(doc, "spend_heatmap.png", width_inch=6.5)
    add_caption(doc, "Figure 7: Average lifetime spend per category and segment (EUR).")
    
    add_image(doc, "fig_seg_metrics.png", width_inch=6.5)
    add_caption(doc, "Figure 8: Key demographic and spend metrics across segments.")

    add_heading_styled(doc, "Segment Profiles", level=2, hex_color="7C3AED")
    for idx in range(5):
        color = SEG_HEX[idx]
        stats = SEG_STATS[idx]
        create_segment_badge_table(doc, SEG_NAMES[idx], color, stats[0], stats[1], stats[2])
        doc.add_paragraph(SEG_DESC[idx])
        add_heading_styled(doc, "Defining Characteristics", level=3, hex_color=HEX_DARK)
        for char in SEG_CHARS[idx]:
            add_bullet(doc, char)
        doc.add_paragraph().paragraph_format.space_after = Pt(6)

    # ════════════════════════════════════════════════════════════════════════════
    # 4   TARGETED PROMOTION
    # ════════════════════════════════════════════════════════════════════════════
    add_heading_styled(doc, "4   Targeted Promotion", level=1, hex_color="D97706")
    doc.add_paragraph(
        "Targeted promotions were designed for each segment using basket association rules mined "
        "via the Apriori algorithm on the customer_basket dataset (min support 1%, min confidence "
        "25%, min lift 1.1). Rules were computed separately per cluster to ensure segment-specific "
        "relevance. Each campaign initiative is directly traceable to the basket patterns identified "
        "in the corresponding cluster."
    )
    
    add_image(doc, "spend_heatmap.png", width_inch=6.5)
    add_caption(doc, "Figure 9: Spend heatmap provides the category context for each campaign initiative.")

    for idx in range(5):
        color = SEG_HEX[idx]
        stats = SEG_STATS[idx]
        create_segment_badge_table(doc, SEG_NAMES[idx], color, stats[0], stats[1], stats[2])
        add_heading_styled(doc, "Campaign Initiatives", level=3, hex_color=HEX_DARK)
        generate_campaign_block(doc, SEG_CAMPAIGNS[idx], color)
        
        rules_list = top_rules.get(str(idx))
        if rules_list:
            add_heading_styled(doc, "Supporting Association Rules (top 3 by lift)", level=3, hex_color=HEX_DARK)
            
            rules_table_data = []
            for ant, cons, sup, conf, lift in rules_list:
                rules_table_data.append([ant, cons, f"{float(sup):.3f}", f"{float(conf):.2%}", f"{float(lift):.2f}"])
            
            generate_styled_table(doc, rules_table_data, 
                                  ["If customer buys", "They also buy", "Support", "Confidence", "Lift"],
                                  col_widths=[1.8, 1.8, 0.8, 1.0, 1.1], hi_col=4)
        else:
            p_none = doc.add_paragraph("No significant rules found at the specified thresholds.")
            p_none.runs[0].font.size = Pt(9)
            p_none.runs[0].font.color.rgb = RGBColor.from_string(HEX_DARK)

    # ════════════════════════════════════════════════════════════════════════════
    # 5   CONCLUSION AND RECOMMENDATIONS
    # ════════════════════════════════════════════════════════════════════════════
    add_heading_styled(doc, "5   Conclusion and Recommendations", level=1, hex_color="0891B2")
    add_heading_styled(doc, "Summary", level=2, hex_color="0891B2")
    doc.add_paragraph(
        "Five meaningfully distinct customer segments were identified through K-Means clustering, "
        "validated by both elbow and silhouette analysis. The segments are differentiated primarily "
        "by category spend composition, household structure, customer tenure and price sensitivity. "
        "Each segment has a coherent behavioural profile that directly supports the targeted and "
        "feasible marketing initiatives proposed in Section 4."
    )

    add_heading_styled(doc, "Segment-Level Recommendations", level=2, hex_color="0891B2")
    recs = [
        ("High-Value Families",
         "Priority retention target. Invest in a VIP loyalty tier with meaningful cashback and milestone "
         "rewards. Family-oriented bundle promotions reinforce natural multi-category purchasing. This is "
         "the highest-ROI segment for any retention spend."),
        ("Core Everyday Shoppers",
         "Largest revenue pool due to segment size. Cross-category promotions in fresh produce and "
         "groceries grow basket size without requiring price discounting on core staples. A weekly "
         "fresh-deal anchor day creates predictable visit cadence."),
        ("Budget-Conscious Shoppers",
         "Loyalty and consolidation are the twin goals. A mid-week loyalty event and household bundle "
         "offers reward in-store consolidation. These customers are highly promotion-responsive, making "
         "structured incentives cost-effective."),
        ("Tech-Savvy Singles",
         "Technology product affinity is strong and basket rules confirm clear co-purchase patterns in "
         "electronics and gaming. Launch-aligned campaigns and device trade-in programmes are the "
         "highest-fit interventions."),
        ("Pet and Home Essentials",
         "Subscription conversion is the strategic priority. High purchase regularity in pet food and "
         "hygiene makes this segment ideally suited for a subscribe-and-save programme that locks in "
         "revenue and raises switching costs.")
    ]
    for title, body in recs:
        add_heading_styled(doc, title, level=3, hex_color=HEX_DARK)
        p_rec = doc.add_paragraph(body)
        p_rec.paragraph_format.space_after = Pt(6)

    add_heading_styled(doc, "Limitations and Future Work", level=2, hex_color="0891B2")
    limitations = [
        "The segmentation uses lifetime aggregates. Recency-weighted features such as RFM metrics may improve separation for detecting churning customers within segments.",
        "The basket dataset contains 100,000 sampled transactions. Association rules for smaller segments - particularly Budget-Conscious Shoppers - have lower statistical power. A larger basket sample would improve rule quality.",
        "Geographic features (latitude, longitude) were excluded as they represent approximate home locations. Incorporating store proximity could further refine cross-shopping patterns in the Budget-Conscious segment.",
        "A temporal analysis of customer transitions between segments would enable early churn detection and dynamic re-targeting as customer behaviour evolves."
    ]
    for lim in limitations:
        add_bullet(doc, lim)

    # Footer Metadata Placement
    p_foot = doc.add_paragraph()
    p_foot.alignment = WD_ALIGN_PARAGRAPH.CENTER
    p_foot.paragraph_format.space_before = Pt(36)
    r_foot = p_foot.add_run("Machine Learning II  |  Nova IMS  |  Data Science Degree")
    r_foot.font.size = Pt(8.5)
    r_foot.font.color.rgb = RGBColor.from_string(HEX_GREY)

    # Save output file
    doc.save(OUTPUT_DOCX)
    print(f"Report built: {OUTPUT_DOCX}")

if __name__ == "__main__":
    build_docx_report()